version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=openai_api_key
      - OPENAI_INSECURE_SKIP_VERIFY=true
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
